#!name = Alight Montion Pro
#!desc = By: Quốc Tín (quctinne)
# Facebook: https://www.facebook.com/quctinne
# Bản quyền thuộc Lê Quốc Tín


[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net

[Script]
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/quoctin75/crack/refs/heads/main/js/alightmotion.js, requires-body=true, timeout=5, tag=Alight Motion
