#!name = Super Duolingo
#!desc = By: Quốc Tín (quctinne)
# Facebook: https://www.facebook.com/quctinne
# Bản quyền thuộc Lê Quốc Tín


[General]
force-http-engine-hosts = *duolingo.com

[Rule]
DOMAIN-SUFFIX,duolingo.com,Proxy
DOMAIN-SUFFIX,duolingo.cn,Proxy
DOMAIN-SUFFIX,duolingo.eu,Proxy
DOMAIN-SUFFIX,duolingo.io,Proxy
DOMAIN-SUFFIX,duolingo.tech,Proxy

[Rewrite]
^https:\/\/(ios-api-2|goals-api|ios-api-cf)\.duolingo\.com\/.*users.* script-path=https://raw.githubusercontent.com/quoctin75/crack/refs/heads/main/js/dulingo.js, requires-body=true, timeout=10, tag=Unlock_Super_Duolingo

[MITM]
hostname = %APPEND% ios-api-2.duolingo.com, goals-api.duolingo.com, ios-api-cf.duolingo.com
