#!name = SoundCloud Go
#!desc = By: Quốc Tín (quctinne)
# Facebook: https://www.facebook.com/quctinne
# Bản quyền thuộc Lê Quốc Tín


[Script]
SoundCloudGo+=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/quoctin75/crack/refs/heads/main/ModuleShadowroket/soundcloud.js
[MITM]
hostname= %APPEND% api-mobile.soundcloud.com
